# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f7yqy3aRDHBf-_760giW-q0FmU4WTQ-p
"""

from setuptools import setup, find_packages

setup(
    name='DatAs',
    version='3.1',
    packages=find_packages(),
    install_requires=[
        'astropy',
        'matplotlib',
        'numpy'
    ],
    author='Sofia fredes, Josefina Navarrete, Nicolas Rojas',
    description='Libreria enfocada en encontrar puntos de interes en base a contraste en imagenes FITS',
    url='https://https://github.com/Sofi1423/DatAs',
)
